### ISSUE TITLE
posten_sensor_next_relative viser feil dag?

### ISSUE THREAD

**Issue by ggflempire** [BobTheShoplifter/HomeAssistant-Posten#16]
Det virker som posten_sensor_next_relative viser feil dag. Min viser "Onsdag" mens i følge posten_sensor_next så er neste leveringsdag Tirsdag

**Comment by BobTheShoplifter** [comment]
@ludeeus You know Why this happens?

**Comment by ludeeus** [comment]
Jepp <https://github.com/BobTheShoplifter/HomeAssistant-Posten/pull/17>
