### ISSUE TITLE
Next relative display wrong date 

### ISSUE THREAD

**Issue by adybnestande** [BobTheShoplifter/HomeAssistant-Posten#18]
The sensor posten_sensor_next_relative shows wrong when the next delivery date is not ‘today’ or ‘tomorrow’. For instance, my posten_sensor_next is reported as 2023-06-13. Today, on 2023-06-11, posten_sensor_next_relative is reported as ‘Onsdag’. However, 2023-06-13 is a Tuesday /‘tirsdag’

**Comment by larsreinhardt** [comment]
![bilde](https://github.com/BobTheShoplifter/HomeAssistant-Posten/assets/34219255/a609961e-4b1e-450c-8c4d-20f64102f389)
this is still an issue, as the 04/07 is a Tuesday

**Comment by larsreinhardt** [comment]
@BobTheShoplifter @ludeeus jeg ser det ligger en retting på dette, men er ikke oppdatert i HACS siste versjon er 0.1.6. Der starter fortsatt uka på mandag

**Comment by BobTheShoplifter** [comment]
Pusher ny versjon!

**Comment by larsreinhardt** [comment]
Sweet @BobTheShoplifter

**Comment by larsreinhardt** [comment]
![bilde](https://github.com/BobTheShoplifter/HomeAssistant-Posten/assets/34219255/6b570bc8-32c5-4322-873f-71d020851750)
Fikset
 @adybnestande

**Comment by adybnestande** [comment]
Great!
