### ISSUE TITLE
Sensor utilgjengelig

### ISSUE THREAD

**Issue by BMK4560** [BobTheShoplifter/HomeAssistant-Posten#19]
Ser ut som integrasjonen døde i natt en gang.

**Comment by BobTheShoplifter** [comment]
Auda :( Skal undersøke når jeg får opp Home Assistant igjen, er nede hjemme atm da jeg har flytta

**Comment by ludeeus** [comment]
![image](https://github.com/BobTheShoplifter/HomeAssistant-Posten/assets/15093472/891986b1-ee17-4928-b1f5-b8a9520c30f6)
😂

**Comment by BobTheShoplifter** [comment]
Har posten igjen ødelagt apiet? 😡

Edit: posta du med token?

**Comment by BobTheShoplifter** [comment]
<img width="991" alt="image" src="https://github.com/BobTheShoplifter/HomeAssistant-Posten/assets/22559547/1a6d3d79-d5ed-4db5-978f-0b1a27d68a7e">

Funker ikke på posten engang

**Comment by ludeeus** [comment]
Med token får jeg 500, er bare første gang jeg har sett 418 (utenom på mine egne servere), var litt morsomt at posten har det også 😄

**Comment by BobTheShoplifter** [comment]
De impimenterte d når de «patcha» oss ut første gang husker jeg haha
________________________________

**Comment by BMK4560** [comment]
å plutselig var den tilbake :-)

**Comment by siggmur** [comment]
Er det bare her den gikk ned igjen?
