### ISSUE TITLE
Add attribute "upcoming" as list of iso8601 dates 

### ISSUE THREAD

**Issue by ccsalvesen** [BobTheShoplifter/HomeAssistant-Posten#2]
A list of upcoming dates would be great for templating. Something like this would be a good start:

```pyhton
import json
from datetime import date
import re

from pprint import pprint

months = ['',
  'januar',
  'februar',
  'mars',
  'april',
  'mai',
  'juni',
  'juli',
  'august',
  'september',
  'oktober',
  'november',
  'desember',
  ]

f = open('delivery_days.json')
json_data = f.read()
f.close()

data = json.loads(json_data)
print('Data structure from api:")
pprint(data)
print("=== === ===")
dates = []
today = date.today()
pprint(today)

for item in data['nextDeliveryDays']:
    match = re.search('(\d\d?)\.\s(\w+)$', item)
    day = int(match.group(1))
    month = months.index(match.group(2).lower())
    year = today.year
    if month < today.month:
        year = year + 1
    dates.append(
        date(
            int(year),
            int(month),
            int(day)
        ).isoformat()
    )


pprint(dates)
```

**Comment by BobTheShoplifter** [comment]
Har du testa https://github.com/ezand/lovelace-posten-card skal funke slik som den funksjonen der, eller er det et ønske om en sensor som gjør dette?

**Comment by ccsalvesen** [comment]
Jeg har prøvd den, men jeg prøver å holde en ren og enkel stil. Den ble litt for stor.

https://github.com/mampfes/hacs_waste_collection_schedule har datoene i en attributt, og det fungerer fint når man bruker mushroom-template-card. 

Jeg kan godt lage en full PR, men jeg så ikke umiddelbart hvor jeg skulle legge til attributten i koden.

**Comment by BobTheShoplifter** [comment]
Når du sier attributt hvor i home assistant er det?

Tenker du her?
![image](https://user-images.githubusercontent.com/22559547/211298203-5fe50cbb-6bfa-491f-a32f-597fe67fa4dd.png)

**Comment by BobTheShoplifter** [comment]
Jeg regner med den dataen også kan brukes i home assistant kalender også?

**Comment by ludeeus** [comment]
Jepp <https://developers.home-assistant.io/docs/core/entity/calendar>

**Comment by BobTheShoplifter** [comment]
![image](https://github.com/user-attachments/assets/e489696a-113a-4c62-8a63-634699d8789d)
Et år for sent kanskje men kommer i neste release!

**Comment by BobTheShoplifter** [comment]
https://github.com/BobTheShoplifter/HomeAssistant-Posten/releases/tag/v0.2.0

Released
