### ISSUE TITLE
Etter HA 2024.2.0 må jeg manuelt reloade Posten er etter restart av HA

### ISSUE THREAD

**Issue by elgeniskogen** [BobTheShoplifter/HomeAssistant-Posten#20]
Takk for fabelaktig integrasjon som er til stor nytte :-)

Etter at jeg oppdaterte til HA 2024.2.0 blir Posten utilgjengelig etter hvet HA restart. Jeg må da gå inn og reloade posten integrasjon manuelt. Etter det funker den bra. Har det noe med ny Python versjon i HA å gjøre? Jeg kan vel lage et script som reloader Posten, men hadde naturligvis vært stas med en fix i selve integrasjonen :-)

mvh Erik :-)

**Comment by NoralfG** [comment]
Samme sak hos meg... :)

**Comment by BobTheShoplifter** [comment]
Spennende, kjører ikke HA hjemme selv lengere så må få satt opp et testmiljø. Har dere en ide om noe som kan ha endra seg?

**Comment by elgeniskogen** [comment]
> Spennende, kjører ikke HA hjemme selv lengere så må få satt opp et testmiljø. Har dere en ide om noe som kan ha endra seg?

Takk for at du følger opp :-) Eneste jeg kan komme på som evt kan påvirke, er ny versjon av Python.

PS Går det ann å kjøre noe annet enn HA? ;-)

**Comment by BobTheShoplifter** [comment]
> > Spennende, kjører ikke HA hjemme selv lengere så må få satt opp et testmiljø. Har dere en ide om noe som kan ha endra seg?
> 
> 
> 
> Takk for at du følger opp :-) Eneste jeg kan komme på som evt kan påvirke, er ny versjon av Python.
> 
> 
> 
> PS Går det ann å kjøre noe annet enn HA? ;-)

Hehe ja, har en homey atm. Driver å skal sette opp en hybrid løsning med begge men må få skaffa meg et rack😅 Hvilken python versjon er de på nå? Ingen feilmeldinger fra addonen?

**Comment by elgeniskogen** [comment]
HA er nå på Python 3.12. Vet ikke om jeg er så god på logging, men satte på logging av Posten integration og restartet.  Vedlagt ligger det jeg fant om Posten i loggen. Håper det hjelper! :-) 

[posten.log](https://github.com/BobTheShoplifter/HomeAssistant-Posten/files/14267738/posten.log)

**Comment by BobTheShoplifter** [comment]
Spennende, skal se om jeg får debugge iløpet av uka!

**Comment by BobTheShoplifter** [comment]
![image](https://github.com/BobTheShoplifter/HomeAssistant-Posten/assets/22559547/cd4c6fda-52cc-4e16-a3de-0c6e4b1963fd)
Okey så tester litt nå og det ser ut som posten funker, selv etter en restart så får jeg ikke opp noen feilmelding i debugmode

**Comment by elgeniskogen** [comment]
Mystisk! Tror den feiler her:
2024-02-14 12:50:00.082 ERROR (MainThread) [custom_components.posten] Timeout error fetching information from https://www.posten.no/levering-av-post/_/service/no.posten.website/delivery-days?postalCode=1350 - 

Kanskje systemet mitt er sausa ned med for mye greier i oppstarten, så den timer ut?! Men jeg har løst det med en automasjon som reloader Posten etter restart så det er kanskje ikke så pisstrengt å bruke mer tid på dette. Tusen takk for innsatsen!!! :-)

**Comment by BobTheShoplifter** [comment]
Kan du adde en enhet med postnummer 7046?

Evt hvilken versjon av pluginen er du på?

**Comment by elgeniskogen** [comment]
Beklager sent svar :-( Kjører versjon 0.1.7. Prøvde med 7046 og da ble begge postnummer unavailable ette restart.

**Comment by BobTheShoplifter** [comment]
Spennende, hvilket setup mer Home Assistant kjører du?

**Comment by elgeniskogen** [comment]
> Spennende, hvilket setup mer Home Assistant kjører du?

Apple Mini, Proxmox, full HA supervised i VM

**Comment by anordnes** [comment]
Har samme greia med min rpi4 2024.2. Må reloade etter restart

**Comment by eriklysoe** [comment]
Samme her på 2024.2.2, må reloade etter start

**Comment by mariwing** [comment]
Samme her også. Bare for å si at det neppe bare gjelder hen som meldte inn opprinnelig. Mine sensorer har heller ikke ordentlige navn; kun underscore mellom ordene.

**Comment by atus** [comment]
Same here. I have the same problem with Mill addon since the HA update as mentioned by OP above.

**Comment by irowan** [comment]
Samme problem her. Må reloade manuelt støtt og stadig.

**Comment by irowan** [comment]
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:533
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 23:29:05 (1 occurrences)
Last logged: 23:29:05

Error adding entities for domain sensor with platform posten
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 533, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 698, in _async_add_entity
    original_icon=entity.icon,
                  ^^^^^^^^^^^
  File "/config/custom_components/posten/sensor.py", line 37, in icon
    if datetime.date.today() == self._next_delivery:
                                ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/posten/entity.py", line 17, in _next_delivery
    *map(int, self.coordinator.data.get("delivery_dates")[0].split("-"))
              ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by BobTheShoplifter** [comment]
Her prøver jeg å spørre @ludeeus i håp om noe, jeg har enda ikke satt opp lokal server så har ikke fått testa. Om noen vet om en form for fiks er det bare å kjøre opp en PR!

**Comment by irowan** [comment]
This error originated from a custom integration.

Logger: custom_components.posten
Source: custom_components/posten/api.py:44
Integration: Når kommer Posten (documentation, issues)
First occurred: March 5, 2024 at 23:34:51 (1 occurrences)
Last logged: March 5, 2024 at 23:34:51

Timeout error fetching information from https://www.posten.no/levering-av-post/_/service/no.posten.website/delivery-days?postalCode=2068 -

**Comment by irowan** [comment]
This error originated from a custom integration.

Logger: custom_components.posten
Source: custom_components/posten/api.py:44
Integration: Når kommer Posten (documentation, issues)
First occurred: March 5, 2024 at 23:34:51 (1 occurrences)
Last logged: March 5, 2024 at 23:34:51

Timeout error fetching information from https://www.posten.no/levering-av-post/_/service/no.posten.website/delivery-days?postalCode=1337 -

**Comment by ludeeus** [comment]
Problemet ligger i at API klienten <https://github.com/BobTheShoplifter/HomeAssistant-Posten/blob/main/custom_components/posten/api.py#L31> returnerer `None` på alle feil isteden for å lage en error.
Dette gjør at når posten sitt API ikke svarer riktig (some Timeout), integrasjonen tro at den fikk riktig respons siden det ikke kom en error.
Men data den bruker er `None`, som gjør at bruken av data feiler.


Jeg foreslår:
- Fjern try/except fra API klient <https://github.com/BobTheShoplifter/HomeAssistant-Posten/blob/main/custom_components/posten/__init__.py#L83> har uansett `Exception` her.
- Legg til logging for feil i coordinator istedenfor i API klienten.

Ved å gjøre dette vill HA automatisk prøve å sette opp integrasjonen på nytt helt frem til den får en riktig response på grunn av disse linjene:
https://github.com/BobTheShoplifter/HomeAssistant-Posten/blob/43c271924a2dd1642b1e572cb62e9ba424607a74/custom_components/posten/__init__.py#L51-L52

**Comment by BobTheShoplifter** [comment]
Da er nye versjonen lagt ut!
