### ISSUE TITLE
Invalid data from API

### ISSUE THREAD

**Issue by krithur** [BobTheShoplifter/HomeAssistant-Posten#23]
0.1.8

**Comment by BobTheShoplifter** [comment]
? What is the error?

**Comment by krithur** [comment]
![image](https://github.com/BobTheShoplifter/HomeAssistant-Posten/assets/157842114/bba167d3-cbaf-4c4c-9b57-73bc3db8ed5e)

**Comment by krithur** [comment]
Ser nå at det muligens er posten som er nede

**Comment by BobTheShoplifter** [comment]
Tjenesten for å finne dager vil være utilgjengelig fredag 21.06. kl. 22.00 til søndag 23.06.2024 kl. 06.00

**Comment by BobTheShoplifter** [comment]
Funker det igjen nå?

**Comment by krithur** [comment]
Alt i orden!
