### ISSUE TITLE
Sensor utilgjengelig etter HACS oppdatering til versjon 2.0.0 

### ISSUE THREAD

**Issue by bmk64** [BobTheShoplifter/HomeAssistant-Posten#24]
Ser ut som sensor posten blir utilgjengelig etter oppdatering av HACS til 2.0..0 ?

**Comment by BobTheShoplifter** [comment]
Oida! Jeg bruker ikke HASS selv noe mer men vet det kom en api endring @ludeeus har du noen peiling?

**Comment by ludeeus** [comment]
Det er ingen 2.0.0 eller 1.34.0 av denne?

**Comment by BobTheShoplifter** [comment]
Tror det er snakk om hass 2.0?

Nei det gir heller ikke mening

**Comment by bmk64** [comment]
My bad...mente selvssagt hacs 2.0.0

**Comment by ludeeus** [comment]
HACS er en nedlaster, hva har det med denne å gjøre?

**Comment by bmk64** [comment]
Søren... Restart er en grei ting :-)  Sorry

**Comment by bmk64** [comment]
Slett gjerne hele posten her :-)

**Comment by BobTheShoplifter** [comment]
Null stress!
