### ISSUE TITLE
Ny enhet legges til etter restart av HA

### ISSUE THREAD

**Issue by BMK4560** [BobTheShoplifter/HomeAssistant-Posten#3]
Etter hver restart legges en ny enhet til under integrasjonen..etter 4 restarter  har jeg nå 5 Enheter istedefor 1.

**Comment by BobTheShoplifter** [comment]
Oisann, skal se på dette asap, tror jeg vet hva problemer er

**Comment by BobTheShoplifter** [comment]
Da er ny versjon ute som fikser feilen, skal kunne oppdatere via hacs

**Comment by BMK4560** [comment]
Den fikset saken :-) thumbs up
