### ISSUE TITLE
Autogenererer flere devices

### ISSUE THREAD

**Issue by Chrulf** [BobTheShoplifter/HomeAssistant-Posten#4]
Jeg la til denne integrationen forrige uke. Siden det har den lagt til mange ekstra (15 stk) devices som på bilde. Kun den siste devicen har sensorene.
Har kun lagt til en gang uten problemer.

![image](https://user-images.githubusercontent.com/109205257/211336185-3ac4acfd-8567-4226-9146-354fcf0da998.png)

![image](https://user-images.githubusercontent.com/109205257/211335808-520582e5-8c9a-4b27-8a17-edeb24a8d2c8.png)

**Comment by BobTheShoplifter** [comment]
Hei! Det skal være en ny versjon (0.1.1) ute på hacs som fikser dette! Prøv en oppdatering og sletting av alle Devices!

**Comment by Chrulf** [comment]
Ah, så ikke den oppdateringen. Satser på det er fikset i den ja :) Takk!
