### ISSUE TITLE
Missing Sensor

### ISSUE THREAD

**Issue by BMK4560** [BobTheShoplifter/HomeAssistant-Posten#7]
Samme problem igjen med posten sensor :-)

**Comment by BobTheShoplifter** [comment]
Uffameg de har endra siden igjen ja… Skal se på det asap
________________________________
From: bmk1964 ***@***.***>
Sent: Wednesday, March 1, 2023 9:16:56 PM
To: BobTheShoplifter/HomeAssistant-Posten ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [BobTheShoplifter/HomeAssistant-Posten] Missing Sensor (Issue #7)


Samme problem igjen med posten sensor :-)

**Comment by Olen** [comment]
Har vi noen idé om hvorfor de endrer det nummeret i URLen hele tida?
Det må være noe magi på gang, for selve posten-appen (i alle fall på Android) er ikke oppdatert nå.

**Comment by BobTheShoplifter** [comment]
Der som kan være mulig er om jeg skriver en slags «proxy». Typ min url som jeg scraper, eventuelt burde man kunne laste inn siden i Python for å så se hva tallet er. Tallet = hvilken seksjon den er i. Feks 11 blokker ned
________________________________

**Comment by Olen** [comment]
Aha. Jeg ser hva som skjer.  VELDIG merkelig måte å drive på.
Men det må ligge ett eller annet annet API i bakgrunnen som mobilappene bruker.

Jeg gravde litt i APK-en til appen, og denne ser lovende ut:
https://api.posten.no/mobile-order/distribution-dates?postalCode=0565

Den gir en "forbidden", og jeg snakker ikke nok Java til å uten videre skjønne hvorfor.  Det er mulig den ikke ligger under api.posten.no men har et annet hostname også.

**Comment by BobTheShoplifter** [comment]
Stemmer! Fant dette apiet jeg også men krever en auth token som man får ved p lage seg bruker :(
________________________________

**Comment by Olen** [comment]
Litt kjapp python som finner riktig seksjon.

```
import requests
from bs4 import BeautifulSoup


posten_url = 'https://www.posten.no/levering-av-post'
html_text = requests.get(posten_url).text
soup = BeautifulSoup(html_text, 'html.parser')

attrs = { "data-portal-region": "leftRegion" }
leftRegion = soup.findAll("div", attrs=attrs)[1].findAll("div", recursive=False)

i = 0
for div in leftRegion:
    if 'class' in div.attrs and 'delivery-days-box' in div.attrs['class']:
        print("We found it!:", i)
    i = i + 1
```

Vet ikke om det er litt mye å dra inn hele bs4 for dette, og den er jo fortsatt litt utsatt for endringer, men kanskje ikke SÅ hyppig som det har vært i det siste.
