### ISSUE TITLE
Missing Sensor

### ISSUE THREAD

**Issue by BMK4560** [BobTheShoplifter/HomeAssistant-Posten#8]
Samme problem igjen med posten sensor :-).

**Comment by BobTheShoplifter** [comment]
Er på TG atm, ser på det når jeg kommer hjem!

**Comment by BMK4560** [comment]
No Worries :-D     
Er ikke noe post alikevel i påske helga :-D

**Comment by BMK4560** [comment]
Ser ut som det løste seg selv :-D
